apiVersion: rc.ccm.dunescience.org/v0alpha0
kind: Partition
metadata:
  name: partition-sample
spec:
  runNumber: 5
  configName: my-first-daq-config
  resources:
  - module: A # one of the four 10kt module names
    TPC:
      APAs:
      - "42"
      - "43"
    PDS:
      APAs:
      - 42-51 # APAs are grouped for PD readout
