# permissions for end users to view daqapplications.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: daqapplication-viewer-role
rules:
- apiGroups:
  - rc.ccm.dunescience.org
  resources:
  - daqapplications
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - rc.ccm.dunescience.org
  resources:
  - daqapplications/status
  verbs:
  - get
