
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - rc.ccm.dunescience.org
  resources:
  - daqapplications
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rc.ccm.dunescience.org
  resources:
  - daqapplications/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - rc.ccm.dunescience.org
  resources:
  - partitions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rc.ccm.dunescience.org
  resources:
  - partitions/status
  verbs:
  - get
  - patch
  - update
