apiVersion: apps/v1
kind: Deployment
metadata:
  name: daq-app-42
  labels:
    app: daq
    apa: "42"
spec:
  selector:
    matchLabels:
      app: daq
      apa: "42"
  replicas: 1
  template:
    metadata:
      labels:
        app: daq
        apa: "42"
    spec:
      tolerations:
      - key: dedicated
        operator: Equal
        value: apa
        effect: NoSchedule
      containers:
      - name: daq
        image: nginx
        ports:
        - containerPort: 80
        resources:
          requests:
            rc.ccm/ru-42-apa-tpc-a: 1
          limits:
            rc.ccm/ru-42-apa-tpc-a: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: daq-app-42-2
  labels:
    app: daq
    apa: "42"
spec:
  selector:
    matchLabels:
      app: daq
      apa: "42"
  replicas: 1
  template:
    metadata:
      labels:
        app: daq
        apa: "42"
    spec:
      tolerations:
      - key: dedicated
        operator: Equal
        value: apa
        effect: NoSchedule
      containers:
      - name: daq
        image: nginx
        ports:
        - containerPort: 80
        resources:
          requests:
            rc.ccm/ru-42-apa-tpc-a: 1
          limits:
            rc.ccm/ru-42-apa-tpc-a: 1