# consul installation docs:
# https://learn.hashicorp.com/tutorials/consul/deployment-guide?in=consul/production-deploy
# nomad installation docs:
# https://learn.hashicorp.com/tutorials/nomad/clustering?in=nomad/manage-clusters

- hosts: all
  tasks:
  - name: install base dependencies
    include_tasks: ../tasks/install-base.yaml

  - name: install hacks
    include_tasks: ../tasks/install-hacks.yaml

  - name: copy consul CA cert
    copy:
      src: consul/consul-agent-ca.pem
      dest: /etc/consul.d/
  
  - name: copy generic consul config
    copy:
      src: consul/consul.hcl
      dest: /etc/consul.d/

- hosts: raft_servers
  tasks:
  - name: copy consul server keys
    copy:
      src: consul/dune-rc-server-consul-{{ inventory_hostname | regex_replace('dune-rc-march-raft-', '') }}-key.pem
      dest: /etc/consul.d/consul-key.pem
  - name: copy consul server certs
    copy:
      src: consul/dune-rc-server-consul-{{ inventory_hostname | regex_replace('dune-rc-march-raft-', '') }}.pem
      dest: /etc/consul.d/consul.pem
  - name: copy consul server config
    template:
      src: consul/server.hcl.template
      dest: /etc/consul.d/server.hcl

- hosts: all:!raft_servers
  tasks:
  - name: copy consul client keys
    copy:
      src: consul/dune-rc-client-consul-{{ inventory_hostname | regex_replace('dune-rc-march-', '') }}-key.pem
      dest: /etc/consul.d/consul-key.pem
  - name: copy consul client certs
    copy:
      src: consul/dune-rc-client-consul-{{ inventory_hostname | regex_replace('dune-rc-march-', '') }}.pem
      dest: /etc/consul.d/consul.pem

- hosts: all
  tasks:
  - name: check if consul is running
    shell: "pgrep consul"
    register: consul_running
    failed_when: consul_running.rc > 1
    changed_when: consul_running.rc == 1
  
  - name: start consul
    when: consul_running.rc == 1
    shell: nohup /usr/bin/consul agent -config-dir=/etc/consul.d/ </dev/null >/dev/null 2>&1 &

  - name: wait until consul healthy
    shell: consul members | wc -l
    register: consul_members
    until: consul_members.stdout == "10"
    changed_when: False
    retries: 90
    delay: 1

- hosts: raft_servers
  tasks:
  - name: copy nomad server config
    template:
      src: nomad/server.hcl.template
      dest: /etc/nomad.d/config.hcl


- hosts: all:!raft_servers
  tasks:
  - name: copy nomad client config
    template:
      src: nomad/client.hcl.template
      dest: /etc/nomad.d/config.hcl

- hosts: all
  tasks:
  - name: check if nomad is running
    shell: "pgrep nomad"
    register: nomad_running
    failed_when: nomad_running.rc > 1
    changed_when: nomad_running.rc == 1
  
  - name: start nomad
    when: nomad_running.rc == 1
    shell: nohup /usr/bin/nomad agent -config=/etc/nomad.d/config.hcl </dev/null >/dev/null 2>&1 &
  - name: wait for nomad
    when: nomad_running.rc == 1
    shell: sleep 10s

- hosts: controllers_host
  tasks:
  - name: install controllers
    include_tasks: ../tasks/install-controllers.yaml