version: "3"

services:
  dune-rc-march-ru-1:
    image: dune-rc-march-ssh-server
  dune-rc-march-ru-2:
    image: dune-rc-march-ssh-server
  dune-rc-march-ru-3:
    image: dune-rc-march-ssh-server
  dune-rc-march-gp-1:
    image: dune-rc-march-ssh-server
  dune-rc-march-gp-2:
    image: dune-rc-march-ssh-server
  dune-rc-march-gp-3:
    image: dune-rc-march-ssh-server

  ansible:
    image: dune-rc-march-ansible
    volumes:
    - ..:/mnt
    entrypoint: ["ansible-playbook"]
    deploy:
      replicas: 0